apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      # Ensure this secret exists in the namespace
      restartPolicy: Always   
      containers:
      - name: mysql
        image: 746936357646.dkr.ecr.us-east-1.amazonaws.com/assignment:mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: yourpassword
