apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      # Ensure this secret exists in the namespace
      restartPolicy: Always 
      containers:
      - name: web
        image: 164340264957.dkr.ecr.us-east-1.amazonaws.com/assignment:webapp
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: mysql-svc.mysql.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DATABASE
          value: employees
        - name: DBPWD
          value: yourpassword
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: currentColor
