apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: ecr-pull-secret # Ensure this secret exists in the namespace
  containers:
  - name: mysql
    image: 746936357646.dkr.ecr.us-east-1.amazonaws.com/assignment:mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: yourpassword
